name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker login -u aryanchy449 -p dckr_pat_uxMjrRQ6juIq8x9i_oqvELPvwlo && docker build . -t aryanchy449/waynefart
    - name: login
      run: docker push aryanchy449/waynefart
